replicaCount: 2

image:
  repository: alternative.cr.de-fra.ionos.com/ckan-alternative
  # repository: ckan-alternative
  tag: v1.0.0
  pullPolicy: IfNotPresent

ckan:
  siteUrl: "siteUrl"
  siteTitle: ALTERNATIVE
  sysadminApiToken: "token"
  smtp:
    server: "server:port"
    user: "user"
    password: "pass"
    mailFrom: "from"

pvc:
  enabled: true
  size: "1Gi"
  storageClassName: "ionos-enterprise-hdd"
  accessmode: "ReadWriteOnce"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 300Mi

keycloakAuthConfig: |
  ckanext.keycloak.server_url = server_url
  ckanext.keycloak.realm = alternative
  ckanext.keycloak.client_id = ckan-backend
  ckanext.keycloak.frontend_client_id = ckan-frontend
  ckanext.keycloak.admin_group = admins
  ckanext.keycloak.client_secret_key = client_secret_key
  ckanext.keycloak.ckan_url = ckan_url
  ckanext.keycloak.ai_ml_api_client_id = ai-ml-api
  ckanext.access_tokens.database_name = postgres
  ckanext.access_tokens.username = postgres
  ckanext.access_tokens.password = pass
  ckanext.access_tokens.host = postgres.demo
  ckanext.access_tokens.table = revoked_tokens
  ckanext.access_tokens.url = access_tokens_url

cloudStorageConfig: |
  ckanext.cloudstorage.driver = S3
  ckanext.cloudstorage.container_name = alternative-datasets
  ckanext.cloudstorage.driver_options = {'host': 's3-eu-central-1.ionoscloud.com', 'key': '', 'secret': '' }

customCKANConfig: |
  ckan.auth.allow_dataset_collaborators = true
  ckan.auth.allow_admin_collaborators = true
  ckan.auth.public_user_details = false
  ckan.activity_streams_email_notifications = true
  ckan.resource_proxy.max_file_size = 1073741824
  ckan.max_resource_size = 1024
  ckan.max_image_size = 1024
  ckanext.cloudstorage.use_secure_urls = false
  ckanext.cloudstorage.leave_files = false

  ## CORS Settings

  # If cors.origin_allow_all is true, all origins are allowed.
  # If false, the cors.origin_whitelist is used.
  ckan.cors.origin_allow_all = false
  # cors.origin_whitelist is a space separated list of allowed domains.
  ckan.cors.origin_whitelist = https://s3-eu-central-1.ionoscloud.com
