---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-ckan
  namespace: alternative
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://alternative.platform.alternative-project.eu
spec:
  rules:
  - host: alternative.ebdfbc2ec9.app.daiteap.com
  tls:
    - hosts:
        - alternative.ebdfbc2ec9.app.daiteap.com
      secretName: ckan-old-tls
