apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "jupyterhub"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/client-max-body-size: "1024m"
spec:
  tls:
  - hosts:
    - "host"
    secretName: "cert-jupyterhub"
  rules:
  - host: "host"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "proxy-public"
            port:
              number: 80