apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-gcs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-gcs-test-sc
  csi:
    volumeAttributes:
      implicitDirs: "true"
    driver: gcs.csi.ofek.dev
    volumeHandle: csi-gcs
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: default
