apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-shared-directory-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi