apiVersion: v2
appVersion: 2.9.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.11.3
- condition: solr.enabled
  name: solr
  repository: https://keitaro-charts.storage.googleapis.com
  version: 1.5.5
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.9.13
- condition: datapusher.enabled
  name: datapusher
  repository: https://keitaro-charts.storage.googleapis.com
  version: 1.0.0
description: CKAN Helm chart
name: ckan
type: application
version: v2.0.4
