apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc 
  namespace: alternative
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: nfs-data