apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "jupyterhub"
  namespace: "default"
spec:
  secretName: "cert-jupyterhub"
  dnsNames:
  - "dnsName"
  issuerRef:
    name: cluster-issuer-letsencrypt
    kind: ClusterIssuer