singleuser:
  image:
    name: gcr.io/alternative-363010/alternative-singleuser
    tag: "v0.0.9"
    pullPolicy: Always
  cmd: /var/alternative-anaconda/init.sh
  storage:
    capacity: 10Gi
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: jupyter-shared-directory-pvc
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/shared
  extraEnv:
    SHELL: /bin/bash
    PATH: /var/alternative-anaconda/anaconda3/bin:/var/alternative-anaconda/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin
hub:
  config:
    GenericOAuthenticator:
      client_id: jupyterhub
      client_secret: client_secret
      oauth_callback_url: oauth_callback_url
      authorize_url: authorize_url
      token_url: token_url
      userdata_url: userdata_url
      login_service: keycloak
      username_key: preferred_username
      auto_login: true
      userdata_params:
        state: state
    JupyterHub:
      authenticator_class: generic-oauth
proxy:
  service:
    type: ClusterIP
