apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
spec:
  destination:
    name: ''
    namespace: nginx-incress
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    chart: ingress-nginx
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true